// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Q6SDK6h3M_MxtyHWg40F75d3kLeudCs',
    appId: '1:579238365079:web:ec22610fe8bdb52adfa6d2',
    messagingSenderId: '579238365079',
    projectId: 'lorenz-app',
    authDomain: 'lorenz-app.firebaseapp.com',
    storageBucket: 'lorenz-app.firebasestorage.app',
    measurementId: 'G-01LP88FH72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg6OvX733R6766KE66a_scE2uw27cdMU0',
    appId: '1:579238365079:android:368d1ee8f2a3ed99dfa6d2',
    messagingSenderId: '579238365079',
    projectId: 'lorenz-app',
    storageBucket: 'lorenz-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg6OvX733R6766KE66a_scE2uw27cdMU0',
    appId: '1:579238365079:ios:PLACEHOLDER',
    messagingSenderId: '579238365079',
    projectId: 'lorenz-app',
    storageBucket: 'lorenz-app.firebasestorage.app',
    iosBundleId: 'com.example.lorenz_app',
  );

}